---
- hosts: localhost
  gather_facts: false

  vars:
    sites:
      - ip: truenas.mabdellatif.net
        token: 1-a7n54o9FmuOpAMibzv4Y7wtCp3MilLafZlRUiZc3mV38SjFxyZi8K8eAhuonTfAz
        validate_certs: false

  tasks:
    - name: update-truenas-api
      include_tasks: truenas_tasks.yaml
      loop: '{{ sites }}'